from __future__ import annotations

from typing import Protocol

from source_aware_worldbuilding.domain.models import (
    ApprovedClaim,
    BibleProjectProfile,
    BibleSection,
    CandidateClaim,
    ClaimRelationship,
    EvidenceSnippet,
    ExtractionOutput,
    ExtractionRun,
    IntakeTextRequest,
    IntakeUrlRequest,
    JobRecord,
    ProjectionSearchResult,
    QueryRequest,
    QueryResult,
    ResearchFetchedPage,
    ResearchFinding,
    ResearchSemanticResult,
    ResearchSearchProviderResult,
    ResearchProgram,
    ResearchRun,
    ResearchScoutCapabilities,
    ResearchSearchHit,
    ReviewEvent,
    SourceDocumentRecord,
    SourceRecord,
    TextUnit,
    ZoteroCreatedItem,
)


class CorpusPort(Protocol):
    def pull_sources(self) -> list[SourceRecord]: ...
    def discover_source_documents(self, sources: list[SourceRecord]) -> list[SourceDocumentRecord]: ...
    def pull_text_units(self, sources: list[SourceRecord]) -> list[TextUnit]: ...
    def pull_sources_by_item_keys(self, item_keys: list[str]) -> list[SourceRecord]: ...
    def create_text_source(self, request: IntakeTextRequest) -> ZoteroCreatedItem: ...
    def create_url_source(self, request: IntakeUrlRequest) -> ZoteroCreatedItem: ...
    def create_file_source(
        self,
        *,
        filename: str,
        content_type: str | None,
        content: bytes,
        title: str | None = None,
        source_type: str = "document",
        notes: str | None = None,
        collection_key: str | None = None,
    ) -> tuple[ZoteroCreatedItem, list[str]]: ...


class ExtractionPort(Protocol):
    def extract_candidates(
        self,
        run: ExtractionRun,
        sources: list[SourceRecord],
        text_units: list[TextUnit],
    ) -> ExtractionOutput: ...


class SourceStorePort(Protocol):
    def list_sources(self) -> list[SourceRecord]: ...
    def get_source(self, source_id: str) -> SourceRecord | None: ...
    def save_sources(self, sources: list[SourceRecord]) -> None: ...


class TextUnitStorePort(Protocol):
    def list_text_units(self, source_id: str | None = None) -> list[TextUnit]: ...
    def save_text_units(self, text_units: list[TextUnit]) -> None: ...


class SourceDocumentStorePort(Protocol):
    def list_source_documents(
        self,
        source_id: str | None = None,
        *,
        ingest_status: str | None = None,
        raw_text_status: str | None = None,
        claim_extraction_status: str | None = None,
    ) -> list[SourceDocumentRecord]: ...
    def save_source_documents(self, source_documents: list[SourceDocumentRecord]) -> None: ...
    def update_source_document(self, source_document: SourceDocumentRecord) -> None: ...


class ExtractionRunStorePort(Protocol):
    def list_runs(self) -> list[ExtractionRun]: ...
    def get_run(self, run_id: str) -> ExtractionRun | None: ...
    def save_run(self, run: ExtractionRun) -> None: ...
    def update_run(self, run: ExtractionRun) -> None: ...


class CandidateStorePort(Protocol):
    def list_candidates(self, review_state: str | None = None) -> list[CandidateClaim]: ...
    def get_candidate(self, candidate_id: str) -> CandidateClaim | None: ...
    def save_candidates(self, candidates: list[CandidateClaim]) -> None: ...
    def update_candidate(self, candidate: CandidateClaim) -> None: ...


class TruthStorePort(Protocol):
    def list_claims(self) -> list[ApprovedClaim]: ...
    def get_claim(self, claim_id: str) -> ApprovedClaim | None: ...
    def list_relationships(self, claim_id: str | None = None) -> list[ClaimRelationship]: ...
    def upsert_relationship(
        self,
        claim_id: str,
        related_claim_id: str,
        relationship_type: str,
        *,
        notes: str | None = None,
        source_kind: str = "manual",
    ) -> ClaimRelationship: ...
    def save_claim(
        self,
        claim: ApprovedClaim,
        evidence: list[EvidenceSnippet] | None = None,
        review: ReviewEvent | None = None,
    ) -> None: ...


class EvidenceStorePort(Protocol):
    def list_evidence(self, source_id: str | None = None) -> list[EvidenceSnippet]: ...
    def get_evidence(self, evidence_id: str) -> EvidenceSnippet | None: ...
    def save_evidence(self, evidence: list[EvidenceSnippet]) -> None: ...


class ReviewStorePort(Protocol):
    def list_reviews(self, candidate_id: str | None = None) -> list[ReviewEvent]: ...
    def save_review(self, review: ReviewEvent) -> None: ...


class ProjectionPort(Protocol):
    def upsert_claims(
        self,
        claims: list[ApprovedClaim],
        evidence: list[EvidenceSnippet],
    ) -> None: ...
    def search_claim_ids(
        self,
        question: str,
        allowed_claim_ids: list[str],
        *,
        limit: int = 10,
    ) -> ProjectionSearchResult: ...


class QueryPort(Protocol):
    def answer(self, request: QueryRequest) -> QueryResult: ...


class ResearchScoutAdapterPort(Protocol):
    @property
    def adapter_id(self) -> str: ...

    @property
    def capabilities(self) -> ResearchScoutCapabilities: ...

    def search(self, query: str, *, limit: int = 5) -> list[ResearchSearchHit]: ...
    def get_last_search_metadata(self) -> dict[str, object] | None: ...
    def fetch_page(self, url: str) -> ResearchFetchedPage: ...
    def allows_fetch(self, url: str, *, user_agent: str) -> bool | None: ...


class ResearchSearchProviderPort(Protocol):
    @property
    def provider_id(self) -> str: ...

    def search(self, query: str, *, limit: int = 5) -> ResearchSearchProviderResult: ...


class ResearchSemanticPort(Protocol):
    def upsert_findings(self, findings: list[ResearchFinding], *, run_id: str) -> int: ...
    def search_similar_findings(
        self,
        finding: ResearchFinding,
        allowed_finding_ids: list[str],
        *,
        run_id: str,
        limit: int = 3,
    ) -> ResearchSemanticResult: ...


class ResearchRunStorePort(Protocol):
    def list_runs(self) -> list[ResearchRun]: ...
    def get_run(self, run_id: str) -> ResearchRun | None: ...
    def save_run(self, run: ResearchRun) -> None: ...
    def update_run(self, run: ResearchRun) -> None: ...


class ResearchFindingStorePort(Protocol):
    def list_findings(self, run_id: str | None = None) -> list[ResearchFinding]: ...
    def save_findings(self, findings: list[ResearchFinding]) -> None: ...
    def update_finding(self, finding: ResearchFinding) -> None: ...


class ResearchProgramStorePort(Protocol):
    def list_programs(self) -> list[ResearchProgram]: ...
    def get_program(self, program_id: str) -> ResearchProgram | None: ...
    def save_program(self, program: ResearchProgram) -> None: ...


class JobStorePort(Protocol):
    def list_jobs(self, *, status: str | None = None) -> list[JobRecord]: ...
    def get_job(self, job_id: str) -> JobRecord | None: ...
    def save_job(self, job: JobRecord) -> None: ...
    def update_job(self, job: JobRecord) -> None: ...


class BibleProjectProfileStorePort(Protocol):
    def list_profiles(self) -> list[BibleProjectProfile]: ...
    def get_profile(self, project_id: str) -> BibleProjectProfile | None: ...
    def save_profile(self, profile: BibleProjectProfile) -> None: ...


class BibleSectionStorePort(Protocol):
    def list_sections(self, project_id: str | None = None) -> list[BibleSection]: ...
    def get_section(self, section_id: str) -> BibleSection | None: ...
    def save_section(self, section: BibleSection) -> None: ...
