window.SOURCEBOUND_SEED_DATA = {
  sources: [
    {
      source_id: "src-1",
      title: "Municipal price records of Rouen",
      author: "City clerk",
      year: "1421",
      source_type: "record",
      locator_hint: "folios 10-14",
      zotero_item_key: null,
    },
    {
      source_id: "src-2",
      title: "Later chronicle of unrest",
      author: "Anonymous chronicler",
      year: "1450",
      source_type: "chronicle",
      locator_hint: "chapter 7",
      zotero_item_key: null,
    },
  ],
  evidence: [
    {
      evidence_id: "evi-1",
      source_id: "src-1",
      locator: "folio 12r",
      text: "Bread prices rose sharply during the winter shortage.",
      text_unit_id: "txt-1",
      span_start: 0,
      span_end: 48,
      notes: "Economic record",
      checksum: null,
    },
    {
      evidence_id: "evi-2",
      source_id: "src-2",
      locator: "chapter 7",
      text: "Townspeople whispered that merchants were withholding grain.",
      text_unit_id: "txt-2",
      span_start: 0,
      span_end: 59,
      notes: "Later chronicle, lower certainty",
      checksum: null,
    },
  ],
  candidates: [
    {
      candidate_id: "cand-1",
      subject: "Rouen bread prices",
      predicate: "rose_during",
      value: "winter shortage",
      claim_kind: "practice",
      status_suggestion: "probable",
      review_state: "approved",
      place: "Rouen",
      time_start: "1421-12-01",
      time_end: "1422-02-28",
      viewpoint_scope: null,
      evidence_ids: ["evi-1"],
      extractor_run_id: "seed-run",
      notes: "Derived from municipal records.",
    },
    {
      candidate_id: "cand-2",
      subject: "Merchant grain hoarding",
      predicate: "rumored_in",
      value: "Rouen",
      claim_kind: "belief",
      status_suggestion: "rumor",
      review_state: "pending",
      place: "Rouen",
      time_start: "1422-01-01",
      time_end: "1422-01-31",
      viewpoint_scope: "townspeople",
      evidence_ids: ["evi-2"],
      extractor_run_id: "seed-run",
      notes: "Rumor, not a verified economic fact.",
    },
  ],
  claims: [
    {
      claim_id: "claim-de6045061b76",
      subject: "Rouen bread prices",
      predicate: "rose_during",
      value: "winter shortage",
      claim_kind: "practice",
      status: "probable",
      place: "Rouen",
      time_start: "1421-12-01",
      time_end: "1422-02-28",
      viewpoint_scope: null,
      author_choice: false,
      evidence_ids: ["evi-1"],
      notes: "Derived from municipal records.",
    },
  ],
  extractionRuns: [
    {
      run_id: "seed-run",
      status: "complete",
      source_count: 2,
      candidate_count: 2,
      started_at: "seeded",
      finished_at: "seeded",
      note: "Seed extraction used to prime the operator console.",
    },
    {
      run_id: "queued-run-002",
      status: "queued",
      source_count: 1,
      candidate_count: 0,
      started_at: "awaiting pull",
      finished_at: null,
      note: "Reserved for the next intake pass.",
    },
  ],
  queryPresets: [
    "What does the record say about bread prices in Rouen?",
    "What claims are still contested or rumor?",
    "Which evidence supports the approved economic claim?",
  ],
};
