window.SOURCEBOUND_SEED_DATA = {
  sources: [
    {
      source_id: "src-1",
      title: "Municipal price records of Rouen",
      author: "City clerk",
      year: "1421",
      source_type: "record",
      locator_hint: "folios 10-14",
      zotero_item_key: null,
    },
    {
      source_id: "src-2",
      title: "Later chronicle of unrest",
      author: "Anonymous chronicler",
      year: "1450",
      source_type: "chronicle",
      locator_hint: "chapter 7",
      zotero_item_key: null,
    },
  ],
  evidence: [
    {
      evidence_id: "evi-1",
      source_id: "src-1",
      locator: "folio 12r",
      text: "Bread prices rose sharply during the winter shortage.",
      text_unit_id: "txt-1",
      span_start: 0,
      span_end: 48,
      notes: "Economic record",
      checksum: null,
    },
    {
      evidence_id: "evi-2",
      source_id: "src-2",
      locator: "chapter 7",
      text: "Townspeople whispered that merchants were withholding grain.",
      text_unit_id: "txt-2",
      span_start: 0,
      span_end: 59,
      notes: "Later chronicle, lower certainty",
      checksum: null,
    },
  ],
  candidates: [
    {
      candidate_id: "cand-1",
      subject: "Rouen bread prices",
      predicate: "rose_during",
      value: "winter shortage",
      claim_kind: "practice",
      status_suggestion: "probable",
      review_state: "approved",
      place: "Rouen",
      time_start: "1421-12-01",
      time_end: "1422-02-28",
      viewpoint_scope: null,
      evidence_ids: ["evi-1"],
      extractor_run_id: "seed-run",
      notes: "Derived from municipal records.",
    },
    {
      candidate_id: "cand-2",
      subject: "Merchant grain hoarding",
      predicate: "rumored_in",
      value: "Rouen",
      claim_kind: "belief",
      status_suggestion: "rumor",
      review_state: "pending",
      place: "Rouen",
      time_start: "1422-01-01",
      time_end: "1422-01-31",
      viewpoint_scope: "townspeople",
      evidence_ids: ["evi-2"],
      extractor_run_id: "seed-run",
      notes: "Rumor, not a verified economic fact.",
    },
  ],
  claims: [
    {
      claim_id: "claim-de6045061b76",
      subject: "Rouen bread prices",
      predicate: "rose_during",
      value: "winter shortage",
      claim_kind: "practice",
      status: "probable",
      place: "Rouen",
      time_start: "1421-12-01",
      time_end: "1422-02-28",
      viewpoint_scope: null,
      author_choice: false,
      evidence_ids: ["evi-1"],
      notes: "Derived from municipal records.",
    },
  ],
  extractionRuns: [
    {
      run_id: "seed-run",
      status: "complete",
      source_count: 2,
      candidate_count: 2,
      started_at: "seeded",
      finished_at: "seeded",
      note: "Seed extraction used to prime the writer workspace.",
    },
    {
      run_id: "queued-run-002",
      status: "queued",
      source_count: 1,
      candidate_count: 0,
      started_at: "awaiting pull",
      finished_at: null,
      note: "Reserved for the next intake pass.",
    },
  ],
  researchRuns: [],
  researchPrograms: [],
  bibleProfile: {
    project_id: "project-greyport",
    project_name: "Greyport Bible",
    era: "1421-1422 winter shortage",
    time_start: "1421-12-01",
    time_end: "1422-02-28",
    geography: "Rouen",
    social_lens: "market workers and townspeople",
    narrative_focus: "scarcity, rumor, and municipal pressure",
    taboo_topics: ["modern slang"],
    desired_facets: ["daily life", "institutions", "economics"],
    tone: "grounded_literary",
    composition_defaults: {
      include_statuses: ["verified", "probable"],
      source_types: ["record", "chronicle"],
      focus: "bread prices and rumor",
    },
  },
  bibleSections: [
    {
      section_id: "section-seed-setting",
      project_id: "project-greyport",
      section_type: "setting_overview",
      title: "Setting Overview",
      content:
        "# Setting Overview\n\n## Verified\n- Rouen bread prices: winter shortage.\n  Sources: Municipal price records of Rouen (folio 12r)\n\n## Probable\n- Merchant grain hoarding: Rouen.\n  Note: surfaced from lower-certainty chronicle material.\n\n## Section Telemetry\n- certainty summary: verified 1, probable 1",
      generated_markdown:
        "# Setting Overview\n\n## Verified\n- Rouen bread prices: winter shortage.\n  Sources: Municipal price records of Rouen (folio 12r)",
      manual_markdown: null,
      generation_filters: {
        focus: "bread prices",
        statuses: ["verified", "probable"],
        source_types: ["record", "chronicle"],
        place: "Rouen",
        viewpoint_scope: null,
        claim_kind: null,
        time_start: "1421-12-01",
        time_end: "1422-02-28",
        relationship_types: [],
      },
      references: {
        claim_ids: ["claim-de6045061b76"],
        evidence_ids: ["evi-1"],
        source_ids: ["src-1"],
        certainty_buckets: ["probable"],
      },
      certainty_summary: { probable: 1 },
      coverage_gaps: ["Daily-life detail is still thin."],
      contradiction_flags: [],
      recommended_next_research: ["Find dated domestic accounts for working households in Rouen."],
      has_manual_edits: false,
      created_at: "2026-04-12T00:00:00+00:00",
      updated_at: "2026-04-12T00:00:00+00:00",
      last_generated_at: "2026-04-12T00:00:00+00:00",
      last_edited_at: null,
    },
  ],
  queryPresets: [
    "What does the record say about bread prices in Rouen?",
    "What claims are still contested or rumor?",
    "Which evidence supports the approved economic claim?",
  ],
};
