window.SOURCEBOUND_SEED_DATA = {
  sources: [
    {
      source_id: "src-price-ledger",
      title: "Municipal price ledger of Rouen",
      author: "Bread office clerks",
      year: "1421",
      source_type: "record",
      locator_hint: "folio 12r",
      zotero_item_key: null,
    },
    {
      source_id: "src-bakers-petition",
      title: "Petition of the Rouen bakers",
      author: "Guild wardens",
      year: "1422",
      source_type: "petition",
      locator_hint: "petition 3",
      zotero_item_key: null,
    },
    {
      source_id: "src-council-ordinance",
      title: "Council grain ordinance",
      author: "Rouen council",
      year: "1422",
      source_type: "ordinance",
      locator_hint: "article 7",
      zotero_item_key: null,
    },
    {
      source_id: "src-council-addendum",
      title: "Council grain ordinance addendum",
      author: "Rouen council",
      year: "1422",
      source_type: "ordinance",
      locator_hint: "addendum 2",
      zotero_item_key: null,
    },
    {
      source_id: "src-ballad",
      title: "Dockside ballad of Saint Romain",
      author: "Unknown singer",
      year: "1435",
      source_type: "broadside",
      locator_hint: "verse 4",
      zotero_item_key: null,
    },
  ],
  evidence: [
    {
      evidence_id: "evi-price-rise",
      source_id: "src-price-ledger",
      locator: "folio 12r",
      text: "Rouen bread prices rose during the winter shortage in 1421, and clerks marked the increase in the municipal ledger.",
      text_unit_id: "txt-price-ledger",
      span_start: 0,
      span_end: 117,
      notes: "Core economics evidence.",
      checksum: null,
    },
    {
      evidence_id: "evi-bread-tokens",
      source_id: "src-bakers-petition",
      locator: "petition 3",
      text: "Bakers in Rouen used household bread tokens during January 1422, and each token marked one ration loaf for a registered hearth.",
      text_unit_id: "txt-bakers-petition",
      span_start: 0,
      span_end: 124,
      notes: "Ration-token detail for daily-life and economics sections.",
      checksum: null,
    },
    {
      evidence_id: "evi-bell-prime",
      source_id: "src-council-ordinance",
      locator: "article 7",
      text: "The council ordinance in Rouen recorded that the grain bell was rung after prime in early January 1422.",
      text_unit_id: "txt-council-ordinance",
      span_start: 0,
      span_end: 103,
      notes: "First bell-time account.",
      checksum: null,
    },
    {
      evidence_id: "evi-bell-terce",
      source_id: "src-council-addendum",
      locator: "addendum 2",
      text: "A revised council ordinance in Rouen recorded that the grain bell was rung after terce in late January 1422.",
      text_unit_id: "txt-council-addendum",
      span_start: 0,
      span_end: 111,
      notes: "Later bell-time revision.",
      checksum: null,
    },
    {
      evidence_id: "evi-blue-lanterns",
      source_id: "src-ballad",
      locator: "verse 4",
      text: "Sailors in Rouen said the Saint Romain shrine lanterns burned blue before the thaw of 1422.",
      text_unit_id: "txt-ballad",
      span_start: 0,
      span_end: 93,
      notes: "Folkloric atmosphere, not settled fact.",
      checksum: null,
    },
  ],
  candidates: [
    {
      candidate_id: "cand-price-rise",
      subject: "Rouen bread prices",
      predicate: "rose_during",
      value: "the winter shortage",
      claim_kind: "practice",
      status_suggestion: "verified",
      review_state: "approved",
      place: "Rouen",
      time_start: "1421-12-01",
      time_end: "1422-02-28",
      viewpoint_scope: null,
      evidence_ids: ["evi-price-rise"],
      extractor_run_id: "seed-run-rouen",
      notes: "Strong anchor from the municipal ledger.",
    },
    {
      candidate_id: "cand-bell-watch",
      subject: "Rouen parish beadles",
      predicate: "were_posted_at",
      value: "the grain bell in 1422",
      claim_kind: "institution",
      status_suggestion: "probable",
      review_state: "pending",
      place: "Rouen",
      time_start: "1422-01-01",
      time_end: "1422-02-28",
      viewpoint_scope: null,
      evidence_ids: ["evi-bell-prime"],
      extractor_run_id: "seed-run-rouen",
      notes: "Readable candidate with enough context to review from the queue.",
    },
    {
      candidate_id: "cand-lantern-omen",
      subject: "Saint Romain shrine lanterns",
      predicate: "were_taken_as",
      value: "an omen before the thaw",
      claim_kind: "belief",
      status_suggestion: "rumor",
      review_state: "needs_edit",
      place: "Rouen",
      time_start: "1422-02-01",
      time_end: "1422-02-28",
      viewpoint_scope: "sailors",
      evidence_ids: ["evi-blue-lanterns"],
      extractor_run_id: "seed-run-rouen",
      notes: "Strong mood, but the reviewer should soften the canon wording.",
    },
    {
      candidate_id: "cand-grain-bell-timing",
      subject: "Rouen grain bell",
      predicate: "rang_after",
      value: "prime and terce in January 1422",
      claim_kind: "institution",
      status_suggestion: "contested",
      review_state: "needs_split",
      place: "Rouen",
      time_start: "1422-01-01",
      time_end: "1422-01-31",
      viewpoint_scope: null,
      evidence_ids: ["evi-bell-prime", "evi-bell-terce"],
      extractor_run_id: "seed-run-rouen",
      notes: "Conflicting evidence should be split into separate reviewable claims.",
    },
  ],
  reviewQueue: [
    {
      candidate_id: "cand-price-rise",
      subject: "Rouen bread prices",
      predicate: "rose_during",
      value: "the winter shortage",
      claim_kind: "practice",
      status_suggestion: "verified",
      review_state: "approved",
      place: "Rouen",
      time_start: "1421-12-01",
      time_end: "1422-02-28",
      viewpoint_scope: null,
      evidence_ids: ["evi-price-rise"],
      extractor_run_id: "seed-run-rouen",
      notes: "Strong anchor from the municipal ledger.",
      claim_text: "Rouen bread prices rose during the winter shortage",
      certainty_suggestion: "verified",
      location_summary: "folio 12r · Rouen · 1421-12-01 to 1422-02-28",
      evidence_quality: "supported",
      weakness_reasons: ["single_snippet"],
      primary_evidence: {
        evidence_id: "evi-price-rise",
        source_id: "src-price-ledger",
        source_title: "Municipal price ledger of Rouen",
        source_type: "record",
        locator: "folio 12r",
        excerpt: "Rouen bread prices rose during the winter shortage in 1421, and clerks marked the increase in the municipal ledger.",
        context_before: "Winter market notes from Rouen show that ",
        context_after: " Clerks repeated the mark beside each weekly grain allotment.",
        span_start: 40,
        span_end: 157,
        text_unit_id: "txt-price-ledger",
        notes: "Core economics evidence.",
      },
      extra_evidence_count: 0,
      evidence_items: [
        {
          evidence_id: "evi-price-rise",
          source_id: "src-price-ledger",
          source_title: "Municipal price ledger of Rouen",
          source_type: "record",
          locator: "folio 12r",
          excerpt: "Rouen bread prices rose during the winter shortage in 1421, and clerks marked the increase in the municipal ledger.",
          context_before: "Winter market notes from Rouen show that ",
          context_after: " Clerks repeated the mark beside each weekly grain allotment.",
          span_start: 40,
          span_end: 157,
          text_unit_id: "txt-price-ledger",
          notes: "Core economics evidence.",
        },
      ],
    },
    {
      candidate_id: "cand-bell-watch",
      subject: "Rouen parish beadles",
      predicate: "were_posted_at",
      value: "the grain bell in 1422",
      claim_kind: "institution",
      status_suggestion: "probable",
      review_state: "pending",
      place: "Rouen",
      time_start: "1422-01-01",
      time_end: "1422-02-28",
      viewpoint_scope: null,
      evidence_ids: ["evi-bell-prime"],
      extractor_run_id: "seed-run-rouen",
      notes: "Readable candidate with enough context to review from the queue.",
      claim_text: "Rouen parish beadles were posted at the grain bell in 1422",
      certainty_suggestion: "probable",
      location_summary: "article 7 · Rouen · 1422-01-01 to 1422-02-28",
      evidence_quality: "supported",
      weakness_reasons: ["single_snippet"],
      primary_evidence: {
        evidence_id: "evi-bell-prime",
        source_id: "src-council-ordinance",
        source_title: "Council grain ordinance",
        source_type: "ordinance",
        locator: "article 7",
        excerpt: "the grain bell was rung after prime in early January 1422",
        context_before: "The council ordinance in Rouen recorded that ",
        context_after: ".",
        span_start: 39,
        span_end: 95,
        text_unit_id: "txt-council-ordinance",
        notes: "First bell-time account.",
      },
      extra_evidence_count: 0,
      evidence_items: [
        {
          evidence_id: "evi-bell-prime",
          source_id: "src-council-ordinance",
          source_title: "Council grain ordinance",
          source_type: "ordinance",
          locator: "article 7",
          excerpt: "the grain bell was rung after prime in early January 1422",
          context_before: "The council ordinance in Rouen recorded that ",
          context_after: ".",
          span_start: 39,
          span_end: 95,
          text_unit_id: "txt-council-ordinance",
          notes: "First bell-time account.",
        },
      ],
    },
    {
      candidate_id: "cand-lantern-omen",
      subject: "Saint Romain shrine lanterns",
      predicate: "were_taken_as",
      value: "an omen before the thaw",
      claim_kind: "belief",
      status_suggestion: "rumor",
      review_state: "needs_edit",
      place: "Rouen",
      time_start: "1422-02-01",
      time_end: "1422-02-28",
      viewpoint_scope: "sailors",
      evidence_ids: ["evi-blue-lanterns"],
      extractor_run_id: "seed-run-rouen",
      notes: "Strong mood, but the reviewer should soften the canon wording.",
      claim_text: "Saint Romain shrine lanterns were taken as an omen before the thaw",
      certainty_suggestion: "rumor",
      location_summary: "verse 4 · Rouen · 1422-02-01 to 1422-02-28",
      evidence_quality: "thin",
      weakness_reasons: ["single_snippet", "missing_span_context"],
      primary_evidence: {
        evidence_id: "evi-blue-lanterns",
        source_id: "src-ballad",
        source_title: "Dockside ballad of Saint Romain",
        source_type: "broadside",
        locator: "verse 4",
        excerpt: "Sailors in Rouen said the Saint Romain shrine lanterns burned blue before the thaw of 1422.",
        context_before: "",
        context_after: "",
        span_start: 0,
        span_end: 93,
        text_unit_id: "txt-ballad",
        notes: "Folkloric atmosphere, not settled fact.",
      },
      extra_evidence_count: 0,
      evidence_items: [
        {
          evidence_id: "evi-blue-lanterns",
          source_id: "src-ballad",
          source_title: "Dockside ballad of Saint Romain",
          source_type: "broadside",
          locator: "verse 4",
          excerpt: "Sailors in Rouen said the Saint Romain shrine lanterns burned blue before the thaw of 1422.",
          context_before: "",
          context_after: "",
          span_start: 0,
          span_end: 93,
          text_unit_id: "txt-ballad",
          notes: "Folkloric atmosphere, not settled fact.",
        },
      ],
    },
    {
      candidate_id: "cand-grain-bell-timing",
      subject: "Rouen grain bell",
      predicate: "rang_after",
      value: "prime and terce in January 1422",
      claim_kind: "institution",
      status_suggestion: "contested",
      review_state: "needs_split",
      place: "Rouen",
      time_start: "1422-01-01",
      time_end: "1422-01-31",
      viewpoint_scope: null,
      evidence_ids: ["evi-bell-prime", "evi-bell-terce"],
      extractor_run_id: "seed-run-rouen",
      notes: "Conflicting evidence should be split into separate reviewable claims.",
      claim_text: "Rouen grain bell rang after prime and terce in January 1422",
      certainty_suggestion: "contested",
      location_summary: "article 7 · Rouen · 1422-01-01 to 1422-01-31",
      evidence_quality: "thin",
      weakness_reasons: ["missing_span_context"],
      primary_evidence: {
        evidence_id: "evi-bell-prime",
        source_id: "src-council-ordinance",
        source_title: "Council grain ordinance",
        source_type: "ordinance",
        locator: "article 7",
        excerpt: "The council ordinance in Rouen recorded that the grain bell was rung after prime in early January 1422.",
        context_before: "",
        context_after: "",
        span_start: 0,
        span_end: 103,
        text_unit_id: "txt-council-ordinance",
        notes: "First bell-time account.",
      },
      extra_evidence_count: 1,
      evidence_items: [
        {
          evidence_id: "evi-bell-prime",
          source_id: "src-council-ordinance",
          source_title: "Council grain ordinance",
          source_type: "ordinance",
          locator: "article 7",
          excerpt: "The council ordinance in Rouen recorded that the grain bell was rung after prime in early January 1422.",
          context_before: "",
          context_after: "",
          span_start: 0,
          span_end: 103,
          text_unit_id: "txt-council-ordinance",
          notes: "First bell-time account.",
        },
        {
          evidence_id: "evi-bell-terce",
          source_id: "src-council-addendum",
          source_title: "Council grain ordinance addendum",
          source_type: "ordinance",
          locator: "addendum 2",
          excerpt: "A revised council ordinance in Rouen recorded that the grain bell was rung after terce in late January 1422.",
          context_before: "",
          context_after: "",
          span_start: 0,
          span_end: 111,
          text_unit_id: "txt-council-addendum",
          notes: "Later bell-time revision.",
        },
      ],
    },
  ],
  claims: [
    {
      claim_id: "claim-market-price",
      subject: "Rouen bread prices",
      predicate: "rose_during",
      value: "the winter shortage",
      claim_kind: "practice",
      status: "verified",
      place: "Rouen",
      time_start: "1421-12-01",
      time_end: "1422-02-28",
      viewpoint_scope: null,
      author_choice: false,
      evidence_ids: ["evi-price-rise"],
      notes: "Strong anchor from the municipal ledger.",
    },
    {
      claim_id: "claim-bread-tokens",
      subject: "Bakers in Rouen",
      predicate: "used",
      value: "household bread tokens",
      claim_kind: "practice",
      status: "probable",
      place: "Rouen",
      time_start: "1422-01-01",
      time_end: "1422-01-31",
      viewpoint_scope: null,
      author_choice: false,
      evidence_ids: ["evi-bread-tokens"],
      notes: "Grounds rationing scenes but still comes from a narrow petition source.",
    },
    {
      claim_id: "claim-blue-lanterns",
      subject: "Saint Romain shrine lanterns",
      predicate: "were_said_to_burn",
      value: "blue before the thaw",
      claim_kind: "belief",
      status: "rumor",
      place: "Rouen",
      time_start: "1422-02-01",
      time_end: "1422-02-28",
      viewpoint_scope: "sailors",
      author_choice: false,
      evidence_ids: ["evi-blue-lanterns"],
      notes: "Useful atmosphere, still explicitly rumor.",
    },
    {
      claim_id: "claim-docks-author-choice",
      subject: "Rouen docks",
      predicate: "should_be_depicted_as",
      value: "narrow, freezing, and lantern-lit",
      claim_kind: "place",
      status: "author_choice",
      place: "Rouen",
      time_start: null,
      time_end: null,
      viewpoint_scope: null,
      author_choice: true,
      evidence_ids: [],
      notes: "Approved drafting default that stays outside strict-fact outputs.",
    },
  ],
  extractionRuns: [
    {
      run_id: "seed-run-rouen",
      status: "completed",
      source_count: 5,
      candidate_count: 4,
      started_at: "seeded",
      finished_at: "seeded",
      note: "Seed extraction used to prime the writer workspace.",
    },
    {
      run_id: "queued-run-rouen",
      status: "queued",
      source_count: 1,
      candidate_count: 0,
      started_at: "awaiting pull",
      finished_at: null,
      note: "Reserved for the next intake pass.",
    },
  ],
  researchRuns: [],
  researchPrograms: [],
  bibleProfile: {
    project_id: "project-rouen-winter",
    project_name: "Rouen Winter Shortage Bible",
    era: "1421-1422 winter shortage",
    time_start: "1421-12-01",
    time_end: "1422-02-28",
    geography: "Rouen",
    social_lens: "bakers, porters, clerks, and households waiting on ration lines",
    narrative_focus: "market control, winter scarcity, rumor, and ritualized public order",
    taboo_topics: ["modern slang", "clean heroic famine myths"],
    desired_facets: ["economics", "daily life", "institutions", "ritual", "rumor"],
    tone: "grounded_literary",
    composition_defaults: {
      include_statuses: ["verified", "probable"],
      source_types: ["record", "petition", "archive", "account_book"],
      focus: "bread prices, ration tokens, and bell-controlled market flow",
    },
  },
  bibleSections: [
    {
      section_id: "section-seed-economics",
      project_id: "project-rouen-winter",
      section_type: "economics_and_material_culture",
      title: "Markets, Tokens, and Grain Flow",
      content:
        "# Economics And Material Culture\n\n## Trade, exchange, and pressure\nTrade pressure is clearest when Rouen bread prices rose during the winter shortage and Bakers in Rouen used household bread tokens. Stage scenes in Rouen, mainly around 1421-12-01 and 1422-01-01. Keep uncertainty bounded: treat Bakers in Rouen used household bread tokens as the working read rather than hard fact. Sources: Municipal price ledger of Rouen (folio 12r); Petition of the Rouen bakers (petition 3).\n\n## Coverage Notes\nCoverage currently supports economics and daily life.",
      generated_markdown:
        "# Economics And Material Culture\n\n## Trade, exchange, and pressure\nTrade pressure is clearest when Rouen bread prices rose during the winter shortage and Bakers in Rouen used household bread tokens. Stage scenes in Rouen, mainly around 1421-12-01 and 1422-01-01. Keep uncertainty bounded: treat Bakers in Rouen used household bread tokens as the working read rather than hard fact. Sources: Municipal price ledger of Rouen (folio 12r); Petition of the Rouen bakers (petition 3).\n\n## Coverage Notes\nCoverage currently supports economics and daily life.",
      manual_markdown: null,
      paragraphs: [
        {
          paragraph_id: "para-seed-econ",
          heading: "Trade, exchange, and pressure",
          text: "Trade pressure is clearest when Rouen bread prices rose during the winter shortage and Bakers in Rouen used household bread tokens. Stage scenes in Rouen, mainly around 1421-12-01 and 1422-01-01. Keep uncertainty bounded: treat Bakers in Rouen used household bread tokens as the working read rather than hard fact. Sources: Municipal price ledger of Rouen (folio 12r); Petition of the Rouen bakers (petition 3).",
          paragraph_kind: "economy_cluster",
          paragraph_role: null,
          claim_ids: ["claim-market-price", "claim-bread-tokens"],
          evidence_ids: ["evi-bread-tokens", "evi-price-rise"],
          source_ids: ["src-bakers-petition", "src-price-ledger"],
          contradiction_flags: [],
          supersession_flags: [],
        },
      ],
      generation_filters: {
        focus: "bread prices, ration tokens, debt tracking, and market movement",
        statuses: ["verified", "probable"],
        source_types: ["record", "petition", "archive", "account_book"],
        place: "Rouen",
        viewpoint_scope: null,
        claim_kind: null,
        time_start: "1421-12-01",
        time_end: "1422-02-28",
        relationship_types: [],
      },
      references: {
        claim_ids: ["claim-bread-tokens", "claim-market-price"],
        evidence_ids: ["evi-bread-tokens", "evi-price-rise"],
        source_ids: ["src-bakers-petition", "src-price-ledger"],
        certainty_buckets: ["verified", "probable"],
      },
      certainty_summary: { verified: 1, probable: 1 },
      coverage_gaps: [],
      contradiction_flags: [],
      recommended_next_research: [],
      coverage_analysis: {
        desired_facets: ["economics", "daily life", "institutions", "ritual", "rumor"],
        facet_distribution: { "daily life": 1, economics: 2, practices: 2 },
        missing_facets: [],
        certainty_mix: { verified: 1, probable: 1 },
        time_coverage: [
          { label: "1421-12-01", count: 1 },
          { label: "1422-01-01", count: 1 },
        ],
        place_coverage: [{ label: "Rouen", count: 2 }],
        missing_named_actors: false,
        missing_material_detail: false,
        missing_dated_anchors: false,
        diagnostic_summary: "Coverage currently supports economics and daily life.",
      },
      retrieval_metadata: {
        retrieval_backend: "memory",
        fallback_used: false,
        fallback_reason: null,
        seed_query: "Economics And Material Culture bread prices, ration tokens, debt tracking, and market movement market control, winter scarcity, rumor, and ritualized public order bakers, porters, clerks, and households waiting on ration lines Rouen 1421-1422 winter shortage economics daily life institutions ritual rumor",
        ranking_strategy: "intent_blended",
      },
      composition_metrics: {
        thin_section: false,
        target_beats: 3,
        produced_beats: 1,
        skipped_beat_ids: ["material_cues", "writer_line"],
        skipped_reasons: ["No paragraph produced for beat 'material_cues'.", "No paragraph produced for beat 'writer_line'."],
        claim_density: 2.0,
        evidence_density: 2.0,
        contradiction_presence: false,
      },
      generation_status: "ready",
      generation_error: null,
      ready_for_writer: true,
      has_manual_edits: false,
      created_at: "2026-04-12T12:20:00+00:00",
      updated_at: "2026-04-12T12:20:00+00:00",
      last_generated_at: "2026-04-12T12:20:00+00:00",
      last_edited_at: null,
    },
    {
      section_id: "section-seed-rumors",
      project_id: "project-rouen-winter",
      section_type: "rumors_and_contested_accounts",
      title: "What the City Said vs. What the Ledgers Say",
      content:
        "# What the City Said vs. What the Ledgers Say\n\nThe working version for the novel keeps rumor and public confusion visible without turning it into narration-level fact.\n\n- Keep the shrine-lantern story in gossip, omen, and mood.\n- Make the grain-bell question feel operational when review clears the contradictory canon.",
      generated_markdown:
        "# Rumors And Contested Accounts\n\nNo approved canon matches this section yet.\n\n## Coverage Notes\nNo approved canon supports rumors and contested accounts yet.\n- No approved canon supports rumors and contested accounts yet.",
      manual_markdown:
        "# What the City Said vs. What the Ledgers Say\n\nThe working version for the novel keeps rumor and public confusion visible without turning it into narration-level fact.\n\n- Keep the shrine-lantern story in gossip, omen, and mood.\n- Make the grain-bell question feel operational when review clears the contradictory canon.",
      paragraphs: [
        {
          paragraph_id: "para-seed-rumor-empty",
          heading: null,
          text: "No approved canon matches this section yet.",
          paragraph_kind: "empty_state",
          paragraph_role: null,
          claim_ids: [],
          evidence_ids: [],
          source_ids: [],
          contradiction_flags: [],
          supersession_flags: [],
        },
      ],
      generation_filters: {
        focus: "grain bell disputes, hoarding stories, and eerie shrine gossip",
        statuses: ["contested", "rumor", "legend", "probable"],
        source_types: ["ordinance", "chronicle", "broadside"],
        place: "Rouen",
        viewpoint_scope: null,
        claim_kind: null,
        time_start: "1421-12-01",
        time_end: "1422-02-28",
        relationship_types: ["contradicts", "supersedes", "superseded_by"],
      },
      references: {
        claim_ids: [],
        evidence_ids: [],
        source_ids: [],
        certainty_buckets: [],
      },
      certainty_summary: {},
      coverage_gaps: ["No approved canon supports rumors and contested accounts yet."],
      contradiction_flags: [],
      recommended_next_research: [],
      coverage_analysis: {
        desired_facets: ["economics", "daily life", "institutions", "ritual", "rumor"],
        facet_distribution: {},
        missing_facets: ["ritual", "rumor"],
        certainty_mix: {},
        time_coverage: [],
        place_coverage: [],
        missing_named_actors: false,
        missing_material_detail: false,
        missing_dated_anchors: false,
        diagnostic_summary: "No approved canon supports rumors and contested accounts yet.",
      },
      retrieval_metadata: {
        retrieval_backend: "memory",
        fallback_used: false,
        fallback_reason: null,
        seed_query: "Rumors And Contested Accounts grain bell disputes, hoarding stories, and eerie shrine gossip market control, winter scarcity, rumor, and ritualized public order bakers, porters, clerks, and households waiting on ration lines Rouen 1421-1422 winter shortage economics daily life institutions ritual rumor",
        ranking_strategy: "intent_blended",
      },
      composition_metrics: {
        thin_section: true,
        target_beats: 0,
        produced_beats: 0,
        skipped_beat_ids: [],
        skipped_reasons: ["No approved canon matched this section."],
        claim_density: 0.0,
        evidence_density: 0.0,
        contradiction_presence: false,
      },
      generation_status: "thin",
      generation_error: null,
      ready_for_writer: false,
      has_manual_edits: true,
      created_at: "2026-04-12T12:45:00+00:00",
      updated_at: "2026-04-12T13:15:00+00:00",
      last_generated_at: "2026-04-12T13:00:00+00:00",
      last_edited_at: "2026-04-12T13:15:00+00:00",
    },
    {
      section_id: "section-seed-author",
      project_id: "project-rouen-winter",
      section_type: "author_decisions",
      title: "House Style Decisions",
      content:
        "# Author Decisions\n\n## Rouen docks\nDrafting default: depict Rouen docks as narrow, freezing, and lantern-lit. Rationale: Approved drafting default that stays outside strict-fact outputs. Keep this in the author-decisions lane rather than presenting it as settled canon in strict-fact outputs.",
      generated_markdown:
        "# Author Decisions\n\n## Rouen docks\nDrafting default: depict Rouen docks as narrow, freezing, and lantern-lit. Rationale: Approved drafting default that stays outside strict-fact outputs. Keep this in the author-decisions lane rather than presenting it as settled canon in strict-fact outputs.",
      manual_markdown: null,
      paragraphs: [
        {
          paragraph_id: "para-seed-author",
          heading: "Rouen docks",
          text: "Drafting default: depict Rouen docks as narrow, freezing, and lantern-lit. Rationale: Approved drafting default that stays outside strict-fact outputs. Keep this in the author-decisions lane rather than presenting it as settled canon in strict-fact outputs.",
          paragraph_kind: "author_guidance",
          paragraph_role: null,
          claim_ids: ["claim-docks-author-choice"],
          evidence_ids: [],
          source_ids: [],
          contradiction_flags: [],
          supersession_flags: [],
        },
      ],
      generation_filters: {
        focus: "narrative defaults for queues, cold weather, and shrine atmosphere",
        statuses: [],
        source_types: [],
        place: "Rouen",
        viewpoint_scope: null,
        claim_kind: null,
        time_start: null,
        time_end: null,
        relationship_types: [],
      },
      references: {
        claim_ids: ["claim-docks-author-choice"],
        evidence_ids: [],
        source_ids: [],
        certainty_buckets: ["author_choice"],
      },
      certainty_summary: { author_choice: 1 },
      coverage_gaps: [],
      contradiction_flags: [],
      recommended_next_research: [],
      coverage_analysis: {
        desired_facets: ["economics", "daily life", "institutions", "ritual", "rumor"],
        facet_distribution: {},
        missing_facets: [],
        certainty_mix: { author_choice: 1 },
        time_coverage: [{ label: "undated", count: 1 }],
        place_coverage: [{ label: "Rouen", count: 1 }],
        missing_named_actors: false,
        missing_material_detail: false,
        missing_dated_anchors: false,
        diagnostic_summary: "Coverage is usable for drafting and stays bounded by approved canon.",
      },
      retrieval_metadata: {
        retrieval_backend: "memory",
        fallback_used: false,
        fallback_reason: null,
        seed_query: "Author Decisions narrative defaults for queues, cold weather, and shrine atmosphere market control, winter scarcity, rumor, and ritualized public order bakers, porters, clerks, and households waiting on ration lines Rouen 1421-1422 winter shortage economics daily life institutions ritual rumor",
        ranking_strategy: "intent_blended",
      },
      composition_metrics: {
        thin_section: false,
        target_beats: 1,
        produced_beats: 1,
        skipped_beat_ids: [],
        skipped_reasons: [],
        claim_density: 1.0,
        evidence_density: 0.0,
        contradiction_presence: false,
      },
      generation_status: "ready",
      generation_error: null,
      ready_for_writer: true,
      has_manual_edits: false,
      created_at: "2026-04-12T13:05:00+00:00",
      updated_at: "2026-04-12T13:05:00+00:00",
      last_generated_at: "2026-04-12T13:05:00+00:00",
      last_edited_at: null,
    },
  ],
  queryPresets: [
    "What does the record say about bread prices in Rouen?",
    "What claims are still contested or rumor?",
    "Which drafting defaults stay outside strict-fact outputs?",
  ],
};
